name: Latest blog post workflow
on:
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://medium.com/@kadambaripatel79'
          fees_list: 'https://medium.com/@kadambaripatel79/creating-awesome-dashboards-in-tableau-a-step-by-step-guide-for-data-analysts-fec0d02d0c10'

          
